# NumPy

## Виртуальное окружение

Но прежде, чем перейдём к основной теме $\text{---}$ есть ещё вещь, которую надо обсудить. Возможно, в этом курсе она не такая уж и важная, но в приличном обществе так делать принято. Я говорю о виртуальном окружении. 

Виртуальное окружение $\text{---}$ это среда, изолирующая набор установленных пакетов и версий Python от системной среды и/или от других проектов. Зачем?
1. Разные проекты могут требовать разные версии одних и тех же библиотек. Если устанавливать их без использования виртуальных окружений (т.е. глобально), то вы неизбежно наткнётесь на несовместимость. Как можете догадаться каждый раз удалять и ставить необходимую версию библиотеки для работы с тем или иным проектом $\text{---}$ не самое увлекательное занятие, поэтому используйте виртуальные окружения.
2. При переходе на другую рабочую машину можно быстро воссоздать используемое [на изначальной машине] окружение (с помощью фиксации списков пакетов в `requirements.txt`, например). Опять же, ничего не сломав при этом новой. 
3. Большое количество пакетов, скаченных однажды для какой-то мелкой задачки, может захламить систему и привести к конфликтам.
4. Возможность использовать несколько разных версий Python (например, для поддержки legacy проектов).

Более "традиционный" способ создавать виртуальные окружения с помощью терминала (и в этом абсолютно нет ничего сложного), но ввиду демонстративных целей данного курса и отсюда максимального упрощения $\text{---}$ мы сделаем это через VSCode.

1. В правом верхнем углу нажимаем кнопку "Select Kernel" (или "Python 3.x.y", где x, y версия Python).

![Select Kernel](pictures/1.png)

2. В появившемся меню нажимаем "Select Another Kernel..."

![Select Another Kernel](pictures/2.png)

3. Нажимаем "Python Environments..."

![Python Environments](pictures/3.png)

4. "Create New Environment..."

![Create New Environment](pictures/4.png)

5. "Venv"

> NB: Если вы используете конду, то вместо `.venv` выберете опцию конды. В шаге 8 изменения должны быть аналогичные.

![Venv](pictures/5.png)

6. "Use Python from \`python.defaultInterpreterPath\` setting

![default path](./pictures/6.png)

7. Ждём пока окошко в правом нижнем углу не пропадёт.

![info](./pictures/7.png)

8. Если на месте кнопки "Select Kernel" или что у вас там было в шаге №1 теперь написано ".venv (Python.3.x.y)", то у вас всё удалось. Слева, в обозревателе (напоминание: если он закрыт, то его можно открыть нажав на пиктограму двух файлов в левом верхнем углу или по комбинации клавиш `Ctrl+B`) должна появиться папка `.venv`. Если решите использовать виртуальное окружение, то не забывайте путь к этой папке (пусть она нужна будет для наших учебных целей).

Если вы не хотите использовать виртуальное окружение (зря), но всё равно выполнили все действия, то прежде, чем перейти дальше -- не забудьте вернуться к глобальной версии (нажав на кнопку выбора ядра и выбрав там то, что вам надо). С другой стороны, если вы уже создали виртуальное окружение, то зачем отказываться им пользоваться, если вещь нужная и полезная? Определитесь сами, а мы продолжим.

## О NumPy

NumPy $\text{---}$ библиотека для научных вычислений. Плюшки:
* Ndarray $\text{---}$ многомерный массив, оптимизированный для быстрых вычислений (скажите спасибо за это C (языку))
* Замена явных циклов на операции над массивами (векторизация), ускоряет вычисления
* Операции линейной алгебры, генерация псевдослучаных чисел, статистические функции и многое другое.

Зачем? Помимо вышеописанного многие библиотеки для МО и ИИ основаны на NumPy, поэтому нужно знать хотя бы его азы.

## Установка

В терминале необходимо выполнить комманду: `pip install numpy` (в случае конды: `conda install numpy`). Если вы используете виртуальное окружение, которое только что создали, то убейте терминал (нажав на пиктограмму мусорного ведра, расположенной на одном уровне с нижними вкладками (среди которых есть вкладка терминала) в правой части) и откройте новый. Ну или закройте/откройте VS Code, как вам удобнее будет.

Если следующая ячейка выполнится корректно, то значит установка прошла успешно.

In [1]:
import numpy as np

Обратим внимение на часть `as np`. `np` $\text{---}$ общепринятое сокращение для NumPy. Если убрать `as np`, то вместо `np` придётся писать `numpy`, поэтому рекомендуется сокращать и рационально использовать сэкономленное время.

## База

### Инициализация векторов и матриц

In [45]:
vec = np.array([1, 2, 3, 4]) # передаём список
matrix = np.array([          # передаём список списков
    [1, 2, 3],
    [4, 5, 6]
])

print(f'Вектор: {vec}')
print(f'Матрица:\n{matrix}\n')

print(f'Размер вектора: {vec.shape}')
print(f'Размер матрицы: {matrix.shape} (строк, столбцов)')
print(f'Длина вектора: {len(vec)}')
print(f'Длина матрицы: {len(matrix)} (sic!)')


Вектор: [1 2 3 4]
Матрица:
[[1 2 3]
 [4 5 6]]

Размер вектора: (4,)
Размер матрицы: (2, 3) (строк, столбцов)
Длина вектора: 4
Длина матрицы: 2 (sic!)


Обратите внимание на последнюю строку. *Длина* матрицы (и другого многомерного объекта) $\text{---}$ это длина *только первого* измерения, а не общее количество элементов. 

Также отметим, что все элементы должны быть одного и того же типа.

In [43]:
vec2 = np.array([1, 2.3, 3, 4])
vec3 = np.array([1, True, False, 4])
vec4 = np.array([1, True, False, 4.])
vec5 = np.array([1, 'х', 2, 3.])

template = '{:4} {:20} {:<21}'
print(template.format('vec',  str(vec),  str(type(vec[0]))))
print(template.format('vec2', str(vec2), str(type(vec2[0]))))
print(template.format('vec3', str(vec3), str(type(vec3[0]))))
print(template.format('vec4', str(vec4), str(type(vec4[0]))))
print(template.format('vec5', str(vec5), str(type(vec5[0]))))

vec  [1 2 3 4]            <class 'numpy.int64'>
vec2 [1.  2.3 3.  4. ]    <class 'numpy.float64'>
vec3 [1 1 0 4]            <class 'numpy.int64'>
vec4 [1. 1. 0. 4.]        <class 'numpy.float64'>
vec5 ['1' 'х' '2' '3.0']  <class 'numpy.str_'> 


<a name="for_curious">Для любознательных</a>: разобраться в коде выше, что именно и как он делает. 

Для всех остальных $\text{---}$ это способ красиво оформить вывод, по сути тоже самое, что и `print(vec, type(vec[0]))`. 

Как видим, при передаче разнородных элементов происходит конвертация:
* Дробное среди целых $\text{---}$ все целые становятся дробным
* Булевая среди целых $\text{---}$ `True` становится `1`, а `False` $\text{---}$ `0`.
* Случай с `vec4` разобрать самостоятельно.
* Строка $\text{---}$ конвертирует всё в строку.

#### Функции инициализации

Функция `zeros` $\text{---}$ инициализирует нулевую матрицу заданного размера (по умолчанию типа `float64`).

In [54]:
zeros_matrix = np.zeros((2, 3)) # передаём кортеж длин измерений:
                                # (строк, столбцов)
print(zeros_matrix, type(zeros_matrix[0,0]))

[[0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.float64'>


Тип можно указывать:

In [48]:
int_zeros_matrix = np.zeros((2, 3), dtype=int)
print(int_zeros_matrix, type(int_zeros_matrix[0,0]))

[[0 0 0]
 [0 0 0]] <class 'numpy.int64'>


`ones` $\text{---}$ матрица, заполненная единицами (*не* единичная матрица).

In [51]:
print(np.ones((2, 3)))

[[1. 1. 1.]
 [1. 1. 1.]]


`full` $\text{---}$ создать и заполнить матрицу значением

In [53]:
print(np.full((2, 3), 6)) # второй (не третий) аргумент -- желаемое значение

[[6 6 6]
 [6 6 6]]


`identity` и `eye` для создания единичных матриц. `identity` $\text{---}$ прямой как палка: даёшь размер (одним числом, т.к. единичная матрица по определению квадратная), получаешь матрицу.

In [55]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
